version: "3"

services:
  postgres:
    image: postgres:14.10-alpine3.18
    container_name: postgres-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  quora-clone-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quora-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_FROM_USER: ${EMAIL_FROM_USER}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app

  nginx: 
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: ngnix
      ports:
        - "80:80"

